/* Totus Central · Presentación única de tarjetas de tarea
   Una acción principal visible; operaciones secundarias en ventana emergente. */
(function(){
  window.taskCard=function(t){
    const p=person(t.assigned_to),mine=t.assigned_to===me().id,running=openTaskTime()?.task_id===t.id,suspended=openTaskInterruption(t.id,t.assigned_to),worked=taskWorkedSeconds(t.id,t.assigned_to),late=t.due_at&&new Date(t.due_at)<new Date()&&!['done','cancelled'].includes(t.status),hasHistory=db.taskTimes.some(x=>x.task_id===t.id),closed=['done','cancelled'].includes(t.status),ov=taskOverrunState(t),ev=taskEvidence(t.id),timeBadge=ov.enabled?`<span class="badge ${ov.left<=0?'badb':ov.left<=10?'warnb':'info'}">${ov.left<=0?'Tiempo agotado':Math.ceil(ov.left)+' min libres'}</span>`:'';
    const primary=mine&&!closed&&canOperate()?(running?`<button class="primary" onclick="stopTaskTimer()">Pausar</button>`:suspended?`<button class="primary" onclick="resumeTask('${t.id}')">Reanudar</button>`:`<button class="primary" onclick="startTaskTimer('${t.id}')">${hasHistory?'Reanudar':'Iniciar'}</button>`):'';
    const requiredEvidence=t.requires_evidence&&!ev.length&&!closed&&(mine||isAdmin())&&canOperate()?`<button class="secondary" onclick="openEvidenceUploader('${t.id}')">Añadir foto</button>`:'';
    const more=(mine||isAdmin()||ev.length)?`<button class="ghost task-more-button" onclick="openTaskActions('${t.id}')">Más opciones</button>`:'';
    return `<div class="task-card ${running?'running':''} ${suspended?'suspended':''}" id="task_${t.id}"><div class="task-title"><div class="grow"><b>${esc(t.title)}</b><div class="task-meta"><span class="badge ${badgeStatus(t.status)}">${taskStatusName(t.status)}</span><span class="badge ${t.priority==='urgent'?'badb':t.priority==='high'?'warnb':'info'}">${priorityName(t.priority)}</span><span class="badge info">${esc(locationName(t.location_id))}</span><span class="badge">${esc(taskCategoryName(t.category_id))}</span>${p?`<span class="badge">${esc(p.name)}</span>`:''}${t.recurrence?.enabled?`<span class="badge info">↻ ${esc(recurrenceText(t.recurrence))}</span>`:''}${t.requires_evidence?'<span class="badge warnb">FOTO REQUERIDA</span>':ev.length?'<span class="badge ok">EVIDENCIA</span>':''}${ev.length?`<span class="badge">${ev.length} archivo${ev.length===1?'':'s'}</span>`:''}${timeBadge}${suspended?'<span class="badge warnb">SUSPENDIDA</span>':''}</div></div><div class="num"><b>${fmtDur(worked)}</b><div class="small">tiempo trabajado</div></div></div>${t.description?`<div class="task-desc">${esc(t.description)}</div>`:''}<div class="meta">${t.starts_at?'Inicio '+dt(t.starts_at)+' · ':''}${t.due_at?(late?'⚠ Venció ':'Vence ')+dt(t.due_at):'Sin vencimiento'} · previsto ${Number(t.estimated_minutes||0)} min</div>${t.requires_evidence&&!ev.length&&!closed?'<div class="warn-note note">Esta tarea necesita una foto o evidencia antes de completarse.</div>':''}${suspended?`<div class="warn-note note"><b>${esc(interruptionName(suspended.reason_code))}</b> · suspendida ${fmtDur(elapsedSec(suspended.started_at))}</div>`:''}${ov.enabled&&ov.left<=0&&!closed&&mine?'<div class="bad-note note">Tiempo autorizado agotado. Debes justificar la ampliación antes de continuar o completar.</div>':''}<div class="task-actions task-actions-compact">${primary}${requiredEvidence}${more}</div></div>`
  };

  window.openTaskActions=function(taskId){
    const t=db.tasks.find(x=>x.id===taskId);if(!t)return;const mine=t.assigned_to===me().id,running=openTaskTime()?.task_id===t.id,suspended=openTaskInterruption(t.id,t.assigned_to),closed=['done','cancelled'].includes(t.status),ov=taskOverrunState(t),ev=taskEvidence(t.id),rows=[];
    if(mine&&!closed&&canOperate()&&running){rows.push(`<button class="task-action-option" onclick="closeModal();resetTaskTimer()"><b>Reiniciar tramo</b><span>Cierra el tramo actual e inicia uno nuevo en la misma tarea.</span></button>`);rows.push(`<button class="task-action-option" onclick="closeModal();suspendTask('${t.id}')"><b>Actividad laboral</b><span>Cliente, proveedor, llamada, reunión o incidencia. Sigue computando trabajo.</span></button>`)}
    if(mine&&!closed&&canOperate()&&suspended)rows.push(`<button class="task-action-option primary-option" onclick="closeModal();resumeTask('${t.id}')"><b>Reanudar tarea</b><span>Finaliza la interrupción laboral y vuelve a contabilizar esta tarea.</span></button>`);
    if((mine||isAdmin())&&canOperate())rows.push(`<button class="task-action-option" onclick="closeModal();openEvidenceUploader('${t.id}')"><b>Añadir foto o evidencia</b><span>${t.requires_evidence?'Necesaria para completar esta tarea.':'Opcional. Úsala solo cuando aporte información.'}</span></button>`);
    if(ev.length)rows.push(`<button class="task-action-option" onclick="closeModal();openTaskEvidence('${t.id}')"><b>Ver evidencias</b><span>${ev.length} archivo${ev.length===1?'':'s'} asociado${ev.length===1?'':'s'}.</span></button>`);
    if(mine&&!closed&&canOperate())rows.push(`<button class="task-action-option" onclick="closeModal();completeTask('${t.id}')"><b>Completar tarea</b><span>Marca el trabajo como terminado conservando todos los tiempos.</span></button>`);
    if(mine&&!closed&&canOperate()&&ov.enabled&&ov.left<=0)rows.push(`<button class="task-action-option danger-option" onclick="closeModal();justifyTaskOverrun('${t.id}')"><b>Justificar ampliación</b><span>El tiempo autorizado está agotado. Registra el motivo para continuar.</span></button>`);
    if(isAdmin())rows.push(`<button class="task-action-option" onclick="closeModal();editTask('${t.id}')"><b>Gestionar tarea</b><span>Asignación, fechas, prioridad, recurrencia y configuración.</span></button>`);
    modal(`<div class="section-head"><div><div class="eyebrow">Tarea</div><h3>${esc(t.title)}</h3><div class="small">${esc(locationName(t.location_id))} · ${esc(taskStatusName(t.status))} · ${fmtDur(taskWorkedSeconds(t.id,t.assigned_to))} trabajados</div></div><button class="ghost" onclick="closeModal()">Cerrar</button></div><div class="task-action-menu-grid">${rows.join('')||'<div class="empty-state compact"><b>Sin acciones disponibles</b><span>Tu rol no permite operaciones adicionales sobre esta tarea.</span></div>'}</div>`)
  };
})();
