/* Totus Central · Usuarios
   Gestión nativa de equipo, acceso, rol y expediente. Sin rutas ni login propios. */
(function(){
  state.nativeUserSearch=state.nativeUserSearch||'';state.nativeUserEmail=state.nativeUserEmail||'';state.nativeAuthUsers=state.nativeAuthUsers||[];
  const admin=()=>typeof isSystemAdmin==='function'?isSystemAdmin():isAdmin();
  const member=email=>(db.team||[]).find(x=>String(x.email||'').toLowerCase()===String(email||'').toLowerCase())||{};
  const profile=email=>(db.people||[]).find(x=>String(x.email||'').toLowerCase()===String(email||'').toLowerCase());
  const auth=email=>(state.nativeAuthUsers||[]).find(x=>String(x.email||'').toLowerCase()===String(email||'').toLowerCase())||{};
  const initials=name=>String(name||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'?';
  const avatar=u=>u?.avatarUrl?`<img src="${esc(u.avatarUrl)}" alt="Foto de ${esc(u.name)}">`:esc(initials(u?.name));
  const fmtAuth=v=>v?dt(v):'Sin acceso todavía';
  const roleOptions=v=>[['admin','Administrador'],['gerente','Gerente'],['encargado','Encargado'],['tendero','Tendero'],['invitado','Invitado · lectura']].map(([k,t])=>`<option value="${k}" ${k===v?'selected':''}>${t}</option>`).join('');

  async function invokeTeamAdmin(payload){const {data,error}=await sb.auth.getSession(),s=data?.session;if(error||!s?.access_token)throw new Error('Sesión no válida.');const res=await fetch(`${SUPABASE_URL}/functions/v1/team-admin`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+s.access_token,'apikey':SUPABASE_KEY},body:JSON.stringify(payload)});let out={};try{out=await res.json()}catch{}if(!res.ok)throw new Error(out?.error||`Error del servidor (${res.status})`);return out}
  window.invokeTeamAdmin=invokeTeamAdmin;
  window.refreshNativeUsers=async function(){if(!admin())return;try{const r=await invokeTeamAdmin({action:'list'});state.nativeAuthUsers=r.users||[]}catch(e){notifyMsg('No se pudo cargar el estado de accesos: '+e.message,'warn',8000)}};
  function rows(){const q=(state.nativeUserSearch||'').trim().toLowerCase();return(db.people||[]).filter(x=>x.active!==false||admin()).filter(x=>!q||[x.name,x.email,x.role,x.jobTitle,x.store].join(' ').toLowerCase().includes(q))}
  function status(u){const a=auth(u.email),m=member(u.email);if(m.active===false)return['badb','Inactivo'];if(a.registered&&a.confirmed)return['ok','Acceso activo'];if(a.registered)return['warnb','Confirmación pendiente'];return['warnb','Sin cuenta']}
  function card(u){const [bc,st]=status(u);return `<button type="button" class="native-user-card ${state.nativeUserEmail===u.email?'selected':''}" onclick="selectNativeUser('${esc(u.email)}')"><div class="native-user-head"><div class="native-user-avatar">${avatar(u)}</div><div class="grow"><h3>${esc(u.name)}</h3><div class="small">${esc(u.email)}</div></div><span class="badge ${bc}">${st}</span></div><div class="native-user-meta"><span class="badge info">${esc(humanRole(u.role))}</span>${u.jobTitle?`<span class="badge">${esc(u.jobTitle)}</span>`:''}</div></button>`}
  function permissions(role){const map={admin:['Configuración','Usuarios','Centros/proyectos','Seguridad','Equipo','Horas','Tareas','Compras','Incidencias','Vacaciones','Documentación','Backup'],gerente:['Equipo','Horas','Tareas','Compras','Incidencias','Vacaciones','Documentación','Informes'],encargado:['Equipo de su ámbito','Horas de su ámbito','Tareas','Incidencias','Vacaciones','Documentación','Informes'],tendero:['Mi jornada','Mis tareas','Mis compras','Mis incidencias','Mis vacaciones','Mis documentos'],invitado:['Lectura autorizada']};return map[role]||[]}
  function permissionPanel(u){return `<section class="card native-permission-panel"><div class="section-head"><div><div class="eyebrow">Permisos</div><h3>${esc(humanRole(u.role))}</h3><div class="small">Los permisos se aplican también en Supabase/RLS.</div></div></div><div class="permission-chip-grid">${permissions(u.role).map(x=>`<span>✓ ${esc(x)}</span>`).join('')}</div></section>`}
  function userEditor(u){if(!u)return `<section class="card native-user-empty"><div class="empty-state big"><b>Selecciona un usuario</b><span>La ficha, seguridad y expediente aparecerán aquí.</span></div></section>`;const m=member(u.email),a=auth(u.email),[bc,st]=status(u);return `<section class="card native-user-editor"><div class="native-user-summary"><div class="native-user-avatar large">${avatar(u)}</div><div class="grow"><b>${esc(u.name)}</b><span>${esc(humanRole(u.role))}${u.jobTitle?' · '+esc(u.jobTitle):''}</span><small>${esc(u.email)}</small></div><span class="badge ${bc}">${st}</span></div><div class="form-grid"><div class="span2"><label>Nombre completo</label><input id="nuName" value="${esc(u.name)}" aria-required="true"></div><div><label>Email / login</label><input value="${esc(u.email)}" disabled></div><div><label>Rol principal</label><select id="nuRole">${roleOptions(u.role)}</select></div><div><label>Teléfono</label><input id="nuPhone" value="${esc(m.phone||'')}"></div><div><label>Puesto / cargo</label><input id="nuJob" value="${esc(m.job_title||u.jobTitle||'')}"></div><div class="span2"><label>Nota operativa interna</label><textarea id="nuNotes" rows="3">${esc(m.employee_notes||'')}</textarea></div></div><div class="actions"><button class="primary" onclick="saveNativeUser('${esc(u.email)}')">Guardar ficha</button><button class="secondary" onclick="openWorkspaceAssignments()">Centros / proyectos</button><button class="secondary" onclick="openUserRecords('${u.id}','documents')">Documentación</button><button class="secondary" onclick="openUserRecords('${u.id}','incidents')">Incidencias</button></div><details class="native-user-security" open><summary>Seguridad y acceso</summary><div class="native-user-security-grid"><div><small>Cuenta</small><b>${a.registered?'Creada':'Sin crear'}</b></div><div><small>Email</small><b>${a.confirmed?'Confirmado':'Pendiente'}</b></div><div><small>Último acceso</small><b>${esc(fmtAuth(a.last_sign_in_at||a.lastSignInAt))}</b></div></div><div class="actions native-security-actions"><button class="secondary" onclick="sendNativeReset('${esc(u.email)}')">Restablecer contraseña</button>${!a.registered?`<button class="secondary" onclick="sendNativeInvite('${esc(u.email)}')">Enviar invitación</button>`:''}${m.active===false?`<button class="primary" onclick="setNativeUserActive('${esc(u.email)}',true)">Activar</button>`:`<button class="danger" onclick="setNativeUserActive('${esc(u.email)}',false)">Desactivar</button>`}<button class="danger" onclick="revokeNativeUser('${esc(u.email)}')">Revocar login</button></div></details></section>${permissionPanel(u)}`}

  window.nativeUsersHtml=function(){if(!admin())return'<div class="empty-state big"><b>Zona restringida</b><span>Usuarios y permisos es exclusivo de administración.</span></div>';const list=rows();if(!state.nativeUserEmail||!profile(state.nativeUserEmail))state.nativeUserEmail=list[0]?.email||'';const selected=profile(state.nativeUserEmail);return `<div class="head"><div><div class="eyebrow">Administración</div><h1>Usuarios</h1><p>Una sola ficha para identidad, acceso, rol, centros y expediente del equipo.</p></div><div class="actions"><button class="secondary" onclick="openWorkspaceAssignments()">Asignar centros</button><button class="primary" onclick="newNativeUser()">+ Nuevo usuario</button></div></div><div class="native-users-master"><section class="card native-users-list"><div class="native-users-toolbar"><div><h3>Listado de usuarios</h3><div class="small">${list.length} usuario${list.length===1?'':'s'}</div></div><label class="native-user-search"><span class="sr-only">Buscar</span><input value="${esc(state.nativeUserSearch)}" placeholder="Buscar nombre, email, rol o puesto…" oninput="state.nativeUserSearch=this.value;renderNativeUsers()"></label></div><div class="native-users-list-scroll">${list.map(card).join('')||'<div class="empty-state"><b>Sin usuarios</b></div>'}</div></section><div class="native-user-detail">${userEditor(selected)}</div></div>`};
  window.renderNativeUsers=function(){const main=document.getElementById('main');if(!main)return;main.innerHTML=nativeUsersHtml()};
  window.selectNativeUser=function(email){state.nativeUserEmail=email;renderNativeUsers()};
  window.openUserRecords=function(uid,sub){if(!uid)return;state.employeeContextUserId=uid;localStorage.setItem('totus_employee_context',uid);if(typeof goRoot==='function')goRoot('tasks',sub)};

  window.saveNativeUser=async function(email){const u=profile(email),m=member(email);if(!u)return;const full_name=document.getElementById('nuName')?.value.trim()||'',role=document.getElementById('nuRole')?.value||'tendero';if(full_name.length<2)return notifyMsg('El nombre es obligatorio.','warn');try{await invokeTeamAdmin({action:'update_member',email,full_name,role,active:m.active!==false,phone:document.getElementById('nuPhone')?.value.trim()||'',job_title:document.getElementById('nuJob')?.value.trim()||'',store:m.store||'',employee_notes:document.getElementById('nuNotes')?.value.trim()||''});await loadDb();await refreshNativeUsers();renderNativeUsers();notifyMsg('Usuario actualizado.')}catch(e){notifyMsg('No se pudo guardar: '+e.message,'bad')}};
  window.setNativeUserActive=async function(email,active){if(!await askConfirm({title:active?'Activar usuario':'Desactivar usuario',message:`${active?'Se permitirá':'Se bloqueará'} el acceso de ${email}. El histórico se conserva.`,confirmText:active?'Activar':'Desactivar',danger:!active}))return;try{await invokeTeamAdmin({action:'set_active',email,active});await loadDb();await refreshNativeUsers();renderNativeUsers();notifyMsg('Estado actualizado.')}catch(e){notifyMsg(e.message,'bad')}};
  window.sendNativeInvite=async function(email){const u=profile(email);try{const r=await invokeTeamAdmin({action:'invite',full_name:u?.name||email,email,role:u?.role||'tendero'});notifyMsg(r.message||'Invitación enviada.');await refreshNativeUsers();renderNativeUsers()}catch(e){notifyMsg('No se pudo enviar la invitación: '+e.message,'bad')}};
  window.sendNativeReset=async function(email){if(!await askConfirm({title:'Restablecer contraseña',message:`Se enviará un correo a ${email} para crear una nueva contraseña en Totus Central.`,confirmText:'Enviar correo'}))return;const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error)return notifyMsg(error.message,'bad');try{await sb.from('team_email_log').insert({recipient_email:email,email_type:'Restablecimiento de contraseña',status:'sent',detail:'Solicitado desde Totus Central',requested_by:session?.user?.email||''})}catch{}notifyMsg('Correo de restablecimiento enviado.')};
  window.revokeNativeUser=async function(email){if(!await askConfirm({title:'Revocar acceso',message:`Se eliminará la cuenta de login de ${email}, pero se conservará la ficha y todo el histórico.`,confirmText:'REVOCAR',danger:true,requireText:'REVOCAR'}))return;try{await invokeTeamAdmin({action:'delete',email});await loadDb();await refreshNativeUsers();renderNativeUsers();notifyMsg('Acceso revocado; histórico conservado.')}catch(e){notifyMsg(e.message,'bad')}};
  window.newNativeUser=function(){modal(`<div class="section-head"><div><div class="eyebrow">Alta</div><h3>Nuevo usuario</h3><div class="small">Crea acceso inmediato o envía una invitación.</div></div><button class="ghost" onclick="closeModal()">Cerrar</button></div><div class="form-grid" style="margin-top:12px"><div class="span2"><label>Nombre completo</label><input id="newNuName" aria-required="true"></div><div class="span2"><label>Email</label><input id="newNuEmail" type="email" aria-required="true"></div><div><label>Rol</label><select id="newNuRole">${roleOptions('tendero')}</select></div><div><label>Contraseña temporal</label><input id="newNuPassword" type="password" placeholder="Opcional si envías invitación"></div></div><div class="actions"><button class="primary" onclick="createNativeUser(false)">Crear con contraseña</button><button class="secondary" onclick="createNativeUser(true)">Enviar invitación</button></div>`)};
  window.createNativeUser=async function(invite){const full_name=document.getElementById('newNuName')?.value.trim()||'',email=document.getElementById('newNuEmail')?.value.trim().toLowerCase()||'',role=document.getElementById('newNuRole')?.value||'tendero',password=document.getElementById('newNuPassword')?.value||'';if(full_name.length<2||!email.includes('@'))return notifyMsg('Nombre y email son obligatorios.','warn');if(!invite&&password.length<8)return notifyMsg('La contraseña temporal debe tener al menos 8 caracteres.','warn');try{await invokeTeamAdmin(invite?{action:'invite',full_name,email,role}:{action:'create_user',full_name,email,role,password});closeModal();await loadDb();await refreshNativeUsers();state.nativeUserEmail=email;renderNativeUsers();notifyMsg(invite?'Invitación enviada.':'Usuario creado.')}catch(e){notifyMsg('No se pudo crear el usuario: '+e.message,'bad')}};
})();