/* Totus Central · Sistema único de relojes
   Jornada, tarea, actividad laboral y parada personal desde una barra permanente. */
(function(){
  const LAST_LOC='totus_clock_last_location',LAST_TASK='totus_clock_last_task',LAST_PERSONAL='totus_clock_last_personal',LAST_WORK='totus_clock_last_work';
  let structuralSignature='',ticker=null;
  const personalOrder=['smoke','snack_unpaid','personal_call','whatsapp_personal','personal_errand','personal_visit','personal_message','personal_other'];
  const workOrder=['customer_attention','sales_rep_visit','order_reception','colleague_call','commercial_call','whatsapp_colleague','inventory_stock','cash_pos_issue','shipment_delivery','work_meeting','work_other'];

  function orderedTypes(kind){const order=kind==='personal'?personalOrder:workOrder,pos=new Map(order.map((x,i)=>[x,i]));return (db.breakTypes||[]).filter(x=>x.active!==false&&(kind==='personal'?x.counts_as_work===false:x.counts_as_work!==false)).slice().sort((a,b)=>(pos.get(a.code)??999)-(pos.get(b.code)??999)||Number(a.sort_order||0)-Number(b.sort_order||0)||String(a.label||'').localeCompare(String(b.label||''),'es'))}
  function tasks(){const uid=me()?.id;return(db.tasks||[]).filter(t=>t.assigned_to===uid&&!['done','cancelled'].includes(t.status)).slice().sort((a,b)=>{const av=a.due_at?+new Date(a.due_at):Number.MAX_SAFE_INTEGER,bv=b.due_at?+new Date(b.due_at):Number.MAX_SAFE_INTEGER;return av-bv||String(a.title||'').localeCompare(String(b.title||''),'es')})}
  function activeTimer(){return typeof openTaskTime==='function'?openTaskTime():null}
  function activeInterruption(){return typeof openTaskInterruption==='function'?openTaskInterruption():null}
  function activeBreak(){return typeof openPersonalBreak==='function'?openPersonalBreak():null}
  function attendance(){return typeof openAttendance==='function'?openAttendance():null}
  function activeTask(){const tt=activeTimer(),i=!tt?activeInterruption():null,id=tt?.task_id||i?.task_id;return id?(db.tasks||[]).find(t=>t.id===id):null}
  function standaloneWork(){const i=activeInterruption();return i&&!i.task_id?i:null}
  function taskMeta(t){if(!t)return'';const loc=t.location_id?locationName(t.location_id):'',due=t.due_at?new Date(t.due_at).toLocaleString('es-ES',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'';return[loc,due&&`vence ${due}`].filter(Boolean).join(' · ')}
  function preferredTask(){const rows=tasks(),stored=localStorage.getItem(LAST_TASK);return rows.some(x=>x.id===stored)?stored:(rows[0]?.id||'')}
  function preferredLocation(){const a=attendance();if(a?.location_id)return a.location_id;const stored=localStorage.getItem(LAST_LOC);if(stored&&(db.locations||[]).some(x=>x.id===stored&&x.active!==false))return stored;return(db.locations||[]).find(x=>x.active!==false)?.id||''}
  function optionTasks(selected){return tasks().map(t=>`<option value="${t.id}" ${t.id===selected?'selected':''}>${esc(t.title)}</option>`).join('')}
  function optionLocations(selected){return(db.locations||[]).filter(x=>x.active!==false).map(x=>`<option value="${x.id}" ${x.id===selected?'selected':''}>${esc(x.name)}</option>`).join('')}
  function optionReasons(kind,selected){return orderedTypes(kind).map(x=>`<option value="${esc(x.code)}" ${x.code===selected?'selected':''}>${esc(x.label)}${x.requires_note?' · detalle':''}</option>`).join('')}
  function signature(){const a=attendance(),tt=activeTimer(),i=activeInterruption(),b=activeBreak();return[me()?.id,a?.id||'',tt?.id||'',i?.id||'',b?.id||'',(db.tasks||[]).map(x=>`${x.id}:${x.status}:${x.updated_at||''}`).join(','),(db.breakTypes||[]).map(x=>`${x.code}:${x.active}:${x.requires_note}:${x.counts_as_work}`).join(',')].join('|')}

  function taskContent(){const a=attendance(),tt=activeTimer(),i=!tt?activeInterruption():null,t=activeTask(),stand=standaloneWork(),rows=tasks(),selected=t?.id||preferredTask();
    if(stand)return `<div class="workbar-task-copy"><b>${esc(interruptionName(stand.reason_code))}</b><small>${esc(locationName(stand.location_id||a?.location_id))} · actividad laboral computable</small></div><div class="workbar-task-actions"><button type="button" class="warning" onclick="clockStopWork()">Finalizar</button></div>`;
    if(i&&t)return `<div class="workbar-task-copy"><b>${esc(t.title)}</b><small>${esc(interruptionName(i.reason_code))} · laboral · computa</small></div><div class="workbar-task-actions"><button type="button" class="start" onclick="clockResumeTask('${t.id}')">Reanudar</button><button type="button" onclick="openActiveTask()">Abrir</button></div>`;
    if(tt&&t)return `<div class="workbar-task-copy"><b title="${esc(t.title)}">${esc(t.title)}</b><small>${esc(taskMeta(t)||'Tarea en marcha')}</small></div><div class="workbar-task-actions"><button type="button" onclick="clockPauseTask()">Pausar</button><button type="button" onclick="openActiveTask()">Abrir</button><button type="button" onclick="clockTaskPicker()">Cambiar</button></div>`;
    if(rows.length)return `<label class="workbar-task-select"><span class="sr-only">Siguiente tarea</span><select id="clockTaskSelect" onchange="clockRememberTask(this.value)">${optionTasks(selected)}</select><small>${esc(taskMeta(rows.find(x=>x.id===selected))||'Selecciona la siguiente tarea')}</small></label><div class="workbar-task-actions"><button type="button" class="start" onclick="clockStartSelected()" ${a&&!activeBreak()?'':'disabled'}>Iniciar</button><button type="button" onclick="clockTaskPicker()">Buscar</button></div>`;
    return `<div class="workbar-task-copy"><b>Sin tareas pendientes</b><small>Revisa o crea trabajo desde Tareas.</small></div><div class="workbar-task-actions"><button type="button" onclick="goRoot('tasks','tasks')">Tareas</button></div>`
  }
  function render(force=false){const host=document.getElementById('shellWorkbar');if(!host||!me())return;const sig=signature();if(!force&&sig===structuralSignature)return;structuralSignature=sig;const a=attendance(),tt=activeTimer(),i=!tt?activeInterruption():null,b=activeBreak(),stand=standaloneWork(),loc=preferredLocation(),taskElapsed=tt?fmtDur(elapsedSec(tt.started_at)):i?fmtDur(elapsedSec(i.started_at)):'00:00:00';
    host.innerHTML=`<div class="workbar-clock ${a?'active':''}"><span>JORNADA</span><strong id="clockAttendanceTime">${a?fmtDur(elapsedSec(a.clock_in)):'00:00:00'}</strong>${a?`<small>${esc(locationName(a.location_id))}</small>`:`<label class="workbar-location-select"><span class="sr-only">Centro</span><select id="clockLocation" onchange="clockRememberLocation(this.value)">${optionLocations(loc)}</select></label>`}</div><div class="workbar-task ${tt||i?'active':''}"><div class="workbar-task-head"><span>${stand?'ACTIVIDAD LABORAL':'TRABAJO'}</span><strong id="clockTaskTime">${taskElapsed}</strong></div>${taskContent()}</div><div class="workbar-clock personal ${b?'active':''}"><span>PARADA</span><strong id="clockBreakTime">${b?fmtDur(elapsedSec(b.started_at)):'00:00:00'}</strong><small>${b?esc(breakName(b.break_type)):'Sin parada personal'}</small></div><div class="workbar-actions"><button type="button" class="${a?'danger-soft':'primary'}" onclick="clockAttendanceToggle()">${a?'Salir':'Entrar'}</button>${b?`<button type="button" class="danger-soft" onclick="clockStopPersonal()">Fin parada</button>`:`<button type="button" onclick="clockPersonalMenu()" ${a&&!i?'':'disabled'}>Parada</button>`}<button type="button" onclick="clockWorkMenu()" ${a&&!b?'':'disabled'}>Laboral</button><button type="button" onclick="clockHelp()">?</button></div>`;
  }
  function refreshTimes(){const a=attendance(),tt=activeTimer(),i=!tt?activeInterruption():null,b=activeBreak(),set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set('clockAttendanceTime',a?fmtDur(elapsedSec(a.clock_in)):'00:00:00');set('clockTaskTime',tt?fmtDur(elapsedSec(tt.started_at)):i?fmtDur(elapsedSec(i.started_at)):'00:00:00');set('clockBreakTime',b?fmtDur(elapsedSec(b.started_at)):'00:00:00')}
  async function reload(){if(typeof reloadTeamData==='function')await reloadTeamData();if(typeof tick==='function')tick();if(typeof renderCurrentRoot==='function'&&['tasks','purchases'].includes(state.root))renderCurrentRoot();render(true)}
  function reasonModal(kind,title,description,onConfirm){const rows=orderedTypes(kind),last=localStorage.getItem(kind==='personal'?LAST_PERSONAL:LAST_WORK),selected=rows.some(x=>x.code===last)?last:(rows[0]?.code||'');window._totusClockReasonSave=onConfirm;modal(`<div class="section-head"><div><div class="eyebrow">Acción rápida</div><h3>${esc(title)}</h3><div class="small">${esc(description)}</div></div><button class="ghost" onclick="closeModal()">Cerrar</button></div><div class="clock-quick-form"><label>Motivo</label><select id="clockReasonCode">${optionReasons(kind,selected)}</select><div id="clockReasonNoteWrap" class="hidden"><label>Detalle breve</label><input id="clockReasonNote" maxlength="300" placeholder="Escribe una frase corta"></div><div class="actions"><button class="primary" onclick="clockSubmitReason('${kind}')">Iniciar</button></div></div>`);const sel=document.getElementById('clockReasonCode'),sync=()=>{const bt=breakType(sel?.value);document.getElementById('clockReasonNoteWrap')?.classList.toggle('hidden',!bt?.requires_note)};sel?.addEventListener('change',sync);sync()}

  window.clockRememberLocation=id=>{if(id)localStorage.setItem(LAST_LOC,id)};
  window.clockRememberTask=id=>{if(id)localStorage.setItem(LAST_TASK,id)};
  window.clockAttendanceToggle=async function(){const a=attendance();if(a){const busy=activeTimer()||activeInterruption()||activeBreak();if(busy)return modal(`<div class="section-head"><div><div class="eyebrow">Cerrar jornada</div><h3>Finaliza los relojes abiertos</h3></div><button class="ghost" onclick="closeModal()">Cerrar</button></div><div class="warn-note note">Antes de salir termina la tarea, actividad laboral o parada personal que siga abierta. Así el día queda conciliado correctamente.</div>`);const {error}=await sb.rpc('attendance_clock_out');if(error)return notifyMsg(error.message,'bad');notifyMsg(`Salida registrada · ${locationName(a.location_id)}.`);return reload()}const loc=document.getElementById('clockLocation')?.value||preferredLocation();if(!loc)return notifyMsg('Selecciona un centro o proyecto.','warn');const {error}=await sb.rpc('attendance_clock_in',{p_location_id:loc});if(error)return notifyMsg(error.message,'bad');localStorage.setItem(LAST_LOC,loc);notifyMsg(`Entrada registrada · ${locationName(loc)}.`);reload()};
  async function startTask(id){if(!attendance())return notifyMsg('Primero ficha entrada.','warn');if(activeBreak())return notifyMsg('Finaliza la parada personal.','warn');if(activeInterruption())return notifyMsg('Finaliza o reanuda la actividad laboral actual.','warn');if(!id)return notifyMsg('Selecciona una tarea.','warn');const {error}=await sb.rpc('task_timer_start',{p_task_id:id});if(error){if(/justificar|agotado|autorizado/i.test(error.message)&&typeof justifyTaskOverrun==='function')return justifyTaskOverrun(id,error.message);return notifyMsg(error.message,'bad')}localStorage.setItem(LAST_TASK,id);notifyMsg(`Tarea iniciada · ${(db.tasks||[]).find(x=>x.id===id)?.title||'Tarea'}.`);reload()}
  window.clockStartSelected=()=>startTask(document.getElementById('clockTaskSelect')?.value||preferredTask());
  window.clockPauseTask=async function(){if(!activeTimer())return;const {error}=await sb.rpc('task_timer_stop');if(error)return notifyMsg(error.message,'bad');notifyMsg('Tarea pausada.');reload()};
  window.clockResumeTask=async function(id){if(!id)return;const {error}=await sb.rpc('task_resume',{p_task_id:id});if(error){if(/justificar|agotado|autorizado/i.test(error.message)&&typeof justifyTaskOverrun==='function')return justifyTaskOverrun(id,error.message);return notifyMsg(error.message,'bad')}localStorage.setItem(LAST_TASK,id);notifyMsg('Tarea reanudada.');reload()};
  window.clockTaskPicker=function(){const rows=tasks();modal(`<div class="section-head"><div><div class="eyebrow">Trabajo</div><h3>Buscar o cambiar de tarea</h3><div class="small">Busca por nombre o descripción sin abandonar la pantalla.</div></div><button class="ghost" onclick="closeModal()">Cerrar</button></div><input id="clockTaskSearch" class="clock-search" placeholder="Buscar tarea…" autocomplete="off" oninput="clockFilterTasks(this.value)"><div id="clockTaskResults" class="workbar-task-results">${clockTaskResultsHtml(rows)}</div>`);setTimeout(()=>document.getElementById('clockTaskSearch')?.focus(),20)};
  window.clockTaskResultsHtml=function(rows){return rows.length?rows.map(t=>`<button class="workbar-result" type="button" onclick="clockChooseTask('${t.id}')"><span><b>${esc(t.title)}</b><small>${esc(taskMeta(t)||'Sin fecha límite')}</small></span><strong>Iniciar →</strong></button>`).join(''):'<div class="empty-state compact"><b>Sin coincidencias</b><span>No hay tareas abiertas con ese texto.</span></div>'};
  window.clockFilterTasks=function(q){const s=String(q||'').trim().toLowerCase(),rows=tasks().filter(t=>!s||`${t.title||''} ${t.description||''}`.toLowerCase().includes(s)),h=document.getElementById('clockTaskResults');if(h)h.innerHTML=clockTaskResultsHtml(rows)};
  window.clockChooseTask=function(id){closeModal();startTask(id)};

  window.clockPersonalMenu=function(){if(!attendance())return notifyMsg('Debes estar fichado.','warn');if(activeBreak())return;reasonModal('personal','Iniciar parada personal','Cigarro, llamada personal, recado, comida no incluida u otra pausa. No computa como trabajo.',async(code,note)=>{const active=activeTimer();if(active)localStorage.setItem(LAST_TASK,active.task_id);const {error}=await sb.rpc('attendance_pause_start',{p_break_type:code,p_notes:note||null});if(error)return notifyMsg(error.message,'bad');notifyMsg(`${breakName(code)} iniciada · NO COMPUTA.`,'warn');reload()})};
  window.clockStopPersonal=async function(){const b=activeBreak();if(!b)return;const {error}=await sb.rpc('attendance_break_stop');if(error)return notifyMsg(error.message,'bad');notifyMsg(`${breakName(b.break_type)} finalizada.`);reload()};
  window.clockWorkMenu=function(){if(!attendance())return notifyMsg('Debes estar fichado.','warn');if(activeBreak())return notifyMsg('Finaliza la parada personal.','warn');if(activeInterruption())return notifyMsg('Ya hay una actividad laboral abierta.','warn');reasonModal('work','Registrar actividad laboral','Cliente, comercial, proveedor, llamada, reunión o incidencia. Este tiempo computa como trabajo.',async(code,note)=>{const tt=activeTimer();let error;if(tt){localStorage.setItem(LAST_TASK,tt.task_id);({error}=await sb.rpc('task_suspend',{p_task_id:tt.task_id,p_reason_code:code,p_reason_note:note||null}))}else({error}=await sb.rpc('work_interruption_start',{p_reason_code:code,p_reason_note:note||null}));if(error)return notifyMsg(error.message,'bad');notifyMsg(`${interruptionName(code)} registrada · COMPUTA como trabajo.`,'warn');reload()})};
  window.clockStopWork=async function(){const i=standaloneWork();if(!i)return;const {error}=await sb.rpc('work_interruption_stop');if(error)return notifyMsg(error.message,'bad');notifyMsg(`${interruptionName(i.reason_code)} finalizada.`);reload()};
  window.clockSubmitReason=function(kind){const code=document.getElementById('clockReasonCode')?.value,bt=breakType(code),note=document.getElementById('clockReasonNote')?.value.trim()||'';if(!bt)return;if(bt.requires_note&&note.length<5)return notifyMsg('Añade un detalle breve de al menos 5 caracteres.','warn');localStorage.setItem(kind==='personal'?LAST_PERSONAL:LAST_WORK,code);const cb=window._totusClockReasonSave;window._totusClockReasonSave=null;closeModal();if(typeof cb==='function')cb(code,note)};
  window.clockHelp=function(){modal(`<div class="section-head"><div><div class="eyebrow">Relojes</div><h3>Control diario en un vistazo</h3></div><button class="ghost" onclick="closeModal()">Cerrar</button></div><div class="quick-help-list"><div><b>Jornada</b><span>Entrada y salida del centro/proyecto en el que trabajas.</span></div><div><b>Trabajo</b><span>Muestra exactamente la tarea o actividad laboral que está contando y permite cambiar de tarea.</span></div><div><b>Parada personal</b><span>Cigarros, llamadas personales, recados o pausas no incluidas. No computan.</span></div><div><b>Actividad laboral</b><span>Clientes, comerciales, reuniones, incidencias o llamadas laborales. Computan aunque no exista una tarea activa.</span></div></div>`)};

  function boot(){render(true);clearInterval(ticker);ticker=setInterval(()=>{refreshTimes();if(signature()!==structuralSignature)render(true)},1000)}
  const baseReload=window.reloadTeamData;if(typeof baseReload==='function')window.reloadTeamData=async function(){const r=await baseReload.apply(this,arguments);requestAnimationFrame(()=>render(true));return r};
  const basePaint=window.paintUser;if(typeof basePaint==='function')window.paintUser=function(){const r=basePaint.apply(this,arguments);requestAnimationFrame(boot);return r};
  requestAnimationFrame(()=>{if(me())boot()});
})();