/* Totus Central · Usuarios nativo
   Gestión de accesos y perfiles sin depender del iframe de Pricing. */
(function(){
  state.nativeUserSearch=state.nativeUserSearch||'';state.nativeUserEmail=state.nativeUserEmail||'';state.nativeAuthUsers=state.nativeAuthUsers||[];
  const admin=()=>typeof isSystemAdmin==='function'?isSystemAdmin():isAdmin();
  function memberByEmail(email){return (db.team||[]).find(x=>String(x.email||'').toLowerCase()===String(email||'').toLowerCase())||{}}
  function profileByEmail(email){return (db.people||[]).find(x=>String(x.email||'').toLowerCase()===String(email||'').toLowerCase())}
  function authByEmail(email){return (state.nativeAuthUsers||[]).find(x=>String(x.email||'').toLowerCase()===String(email||'').toLowerCase())||{}}
  function initials(name='?'){return String(name).trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'?'}
  function avatar(u){return u?.avatarUrl?`<img src="${esc(u.avatarUrl)}" alt="Foto de ${esc(u.name)}">`:esc(initials(u?.name))}
  function fmtAuth(v){return v?dt(v):'Sin acceso todavía'}
  function roleOptions(v){return [['admin','Administrador'],['gerente','Gerente'],['encargado','Encargado'],['tendero','Tendero'],['invitado','Invitado · lectura']].map(([k,t])=>`<option value="${k}" ${k===v?'selected':''}>${t}</option>`).join('')}

  async function invokeTeamAdmin(payload){
    const {data,error}=await sb.auth.getSession();const s=data?.session;if(error||!s?.access_token)throw new Error('Sesión no válida.');
    const res=await fetch(`${SUPABASE_URL}/functions/v1/team-admin`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+s.access_token,'apikey':SUPABASE_KEY},body:JSON.stringify(payload)});let out={};try{out=await res.json()}catch{}if(!res.ok)throw new Error(out?.error||`Error del servidor (${res.status})`);return out
  }
  window.refreshNativeUsers=async function(){if(!admin())return;try{const r=await invokeTeamAdmin({action:'list'});state.nativeAuthUsers=r.users||[]}catch(e){notifyMsg('No se pudo cargar el estado de accesos: '+e.message,'warn',8000)}};

  function filtered(){const q=(state.nativeUserSearch||'').trim().toLowerCase();return (db.people||[]).filter(x=>x.active!==false||admin()).filter(x=>!q||[x.name,x.email,x.role,x.jobTitle,x.store].join(' ').toLowerCase().includes(q))}
  function authStatus(u){const a=authByEmail(u.email);if(a.registered&&a.confirmed)return['ok','Acceso activo'];if(a.registered)return['warnb','Confirmación pendiente'];return['warnb','Sin cuenta']}
  function userCard(u){const m=memberByEmail(u.email),a=authByEmail(u.email),[bc,st]=authStatus(u);return `<article class="native-user-card ${state.nativeUserEmail===u.email?'selected':''}"><div class="native-user-head"><div class="native-user-avatar">${avatar(u)}</div><div class="grow"><h3>${esc(u.name)}</h3><div class="small">${esc(u.email)}</div></div><span class="badge ${m.active===false?'badb':bc}">${m.active===false?'INACTIVO':st}</span></div><div class="native-user-meta"><span class="badge info">${esc(humanRole(u.role))}</span>${u.jobTitle?`<span class="badge">${esc(u.jobTitle)}</span>`:''}</div><div class="native-user-foot"><div class="small">Último acceso: ${esc(fmtAuth(a.last_sign_in_at||a.lastSignInAt))}</div><button class="secondary" onclick="openNativeUser('${esc(u.email)}')">Gestionar</button></div></article>`}

  window.nativeUsersHtml=function(){
    if(!admin())return '<div class="empty-state big"><b>Zona restringida</b><span>Usuarios y permisos es exclusivo de administración.</span></div>';
    const rows=filtered();return `<div class="head"><div><div class="eyebrow">Administración</div><h1>Usuarios</h1><p>Acceso, rol, ficha y seguridad del equipo dentro de Totus Central. No depende de Pricing.</p></div><div class="actions"><button class="secondary" onclick="openWorkspaceAssignments()">Asignar centros</button><button class="primary" onclick="newNativeUser()">+ Nuevo usuario</button></div></div><div class="card native-users-toolbar"><div><h3>Equipo</h3><div class="small">${rows.length} usuario${rows.length===1?'':'s'} visibles</div></div><label class="native-user-search"><span class="sr-only">Buscar usuario</span><input value="${esc(state.nativeUserSearch)}" placeholder="Buscar nombre, email, rol o puesto…" oninput="state.nativeUserSearch=this.value;renderNativeUsers()"></label></div><div class="native-users-grid">${rows.map(userCard).join('')||'<div class="empty-state"><b>Sin usuarios</b></div>'}</div>${roleGuideHtml()}`
  };
  function roleGuideHtml(){return `<div class="card native-role-guide"><div class="section-head"><div><div class="eyebrow">Permisos</div><h3>Qué significa cada rol</h3></div></div><div class="role-guide-grid"><div><b>Administrador</b><span>Configuración completa, usuarios, centros, backups y mantenimiento.</span></div><div><b>Gerente</b><span>Supervisión operativa global, planificación, fichajes e informes.</span></div><div><b>Encargado</b><span>Supervisa y planifica dentro de sus centros/proyectos asignados.</span></div><div><b>Tendero</b><span>Operativa propia: jornada, tareas, compras y solicitudes.</span></div><div><b>Invitado</b><span>Lectura autorizada sin operaciones.</span></div></div></div>`}

  window.renderNativeUsers=function(){const main=document.getElementById('main');if(!main)return;main.classList.remove('hidden');document.getElementById('iframeShell')?.classList.add('hidden');main.innerHTML=nativeUsersHtml();requestAnimationFrame(()=>document.body.classList.add('totus-shell-ready'))};
  window.openNativeUser=function(email){const u=profileByEmail(email),m=memberByEmail(email),a=authByEmail(email);if(!u)return;state.nativeUserEmail=email;modal(`<div class="section-head"><div><div class="eyebrow">Usuario</div><h3>${esc(u.name)}</h3><div class="small">${esc(email)}</div></div><button class="ghost" onclick="closeModal()">Cerrar</button></div><div class="native-user-editor"><div class="native-user-summary"><div class="native-user-avatar large">${avatar(u)}</div><div><b>${esc(u.name)}</b><span>${esc(humanRole(u.role))}${u.jobTitle?' · '+esc(u.jobTitle):''}</span><small>${a.registered?(a.confirmed?'Cuenta confirmada':'Cuenta pendiente de confirmar'):'Cuenta de acceso no creada'}</small></div></div><div class="form-grid"><div class="span2"><label>Nombre completo</label><input id="nuName" value="${esc(u.name)}"></div><div><label>Rol</label><select id="nuRole">${roleOptions(u.role)}</select></div><div><label>Teléfono</label><input id="nuPhone" value="${esc(m.phone||'')}"></div><div class="span2"><label>Puesto / cargo</label><input id="nuJob" value="${esc(m.job_title||u.jobTitle||'')}"></div><div class="span2"><label>Notas internas</label><textarea id="nuNotes" rows="4">${esc(m.employee_notes||'')}</textarea></div></div><div class="actions"><button class="primary" onclick="saveNativeUser('${esc(email)}')">Guardar ficha</button><button class="secondary" onclick="sendNativeReset('${esc(email)}')">Restablecer contraseña</button>${!a.registered?`<button class="secondary" onclick="sendNativeInvite('${esc(email)}')">Enviar invitación</button>`:''}${m.active===false?`<button class="primary" onclick="setNativeUserActive('${esc(email)}',true)">Activar</button>`:`<button class="danger" onclick="setNativeUserActive('${esc(email)}',false)">Desactivar</button>`}</div><details class="native-user-security"><summary>Seguridad y acceso</summary><div class="native-user-security-grid"><div><small>Creada</small><b>${esc(fmtAuth(a.auth_created_at||a.created_at))}</b></div><div><small>Último acceso</small><b>${esc(fmtAuth(a.last_sign_in_at||a.lastSignInAt))}</b></div><div><small>Email</small><b>${a.confirmed?'Confirmado':'Pendiente'}</b></div></div><div class="danger-zone"><button class="danger" onclick="revokeNativeUser('${esc(email)}')">Revocar cuenta de acceso</button></div></details></div>`)};

  window.saveNativeUser=async function(email){const u=profileByEmail(email),m=memberByEmail(email);if(!u)return;const full_name=document.getElementById('nuName')?.value.trim()||'',role=document.getElementById('nuRole')?.value||'tendero';if(full_name.length<2)return notifyMsg('El nombre es obligatorio.','warn');try{await invokeTeamAdmin({action:'update_member',email,full_name,role,active:m.active!==false,phone:document.getElementById('nuPhone')?.value.trim()||'',job_title:document.getElementById('nuJob')?.value.trim()||'',store:m.store||'',employee_notes:document.getElementById('nuNotes')?.value.trim()||''});closeModal();await loadDb();await refreshNativeUsers();renderNativeUsers();notifyMsg('Usuario actualizado.')}catch(e){notifyMsg('No se pudo guardar: '+e.message,'bad')}};
  window.setNativeUserActive=async function(email,active){if(!await askConfirm({title:active?'Activar usuario':'Desactivar usuario',message:`${active?'Se permitirá':'Se bloqueará'} el acceso de ${email}. El histórico se conserva.`,confirmText:active?'Activar':'Desactivar',danger:!active}))return;try{await invokeTeamAdmin({action:'set_active',email,active});closeModal();await loadDb();await refreshNativeUsers();renderNativeUsers();notifyMsg('Estado actualizado.')}catch(e){notifyMsg(e.message,'bad')}};
  window.sendNativeInvite=async function(email){const u=profileByEmail(email);try{const r=await invokeTeamAdmin({action:'invite',full_name:u?.name||email,email,role:u?.role||'tendero'});notifyMsg(r.message||'Invitación enviada.');await refreshNativeUsers();openNativeUser(email)}catch(e){notifyMsg('No se pudo enviar la invitación: '+e.message,'bad')}};
  window.sendNativeReset=async function(email){if(!await askConfirm({title:'Restablecer contraseña',message:`Se enviará un correo a ${email} para crear una nueva contraseña en Totus Central.`,confirmText:'Enviar correo'}))return;const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error)return notifyMsg(error.message,'bad');try{await sb.from('team_email_log').insert({recipient_email:email,email_type:'Restablecimiento de contraseña',status:'sent',detail:'Solicitado desde Totus Central',requested_by:session?.user?.email||''})}catch{}notifyMsg('Correo de restablecimiento enviado.')};
  window.revokeNativeUser=async function(email){if(!await askConfirm({title:'Revocar acceso',message:`Se eliminará la cuenta de login de ${email}, pero se conservará su ficha e histórico.`,confirmText:'REVOCAR',danger:true,requireText:'REVOCAR'}))return;try{await invokeTeamAdmin({action:'delete',email});closeModal();await loadDb();await refreshNativeUsers();renderNativeUsers();notifyMsg('Acceso revocado; histórico conservado.')}catch(e){notifyMsg(e.message,'bad')}};

  window.newNativeUser=function(){modal(`<div class="section-head"><div><div class="eyebrow">Alta</div><h3>Nuevo usuario</h3><div class="small">Puedes crear acceso inmediato o enviar una invitación.</div></div><button class="ghost" onclick="closeModal()">Cerrar</button></div><div class="form-grid" style="margin-top:12px"><div class="span2"><label>Nombre completo</label><input id="newNuName" aria-required="true"></div><div class="span2"><label>Email</label><input id="newNuEmail" type="email" aria-required="true"></div><div><label>Rol</label><select id="newNuRole">${roleOptions('tendero')}</select></div><div><label>Contraseña temporal</label><input id="newNuPassword" type="password" placeholder="Opcional si envías invitación"></div></div><div class="actions"><button class="primary" onclick="createNativeUser(false)">Crear con contraseña</button><button class="secondary" onclick="createNativeUser(true)">Enviar invitación</button></div>`)};
  window.createNativeUser=async function(invite){const full_name=document.getElementById('newNuName')?.value.trim()||'',email=document.getElementById('newNuEmail')?.value.trim().toLowerCase()||'',role=document.getElementById('newNuRole')?.value||'tendero',password=document.getElementById('newNuPassword')?.value||'';if(full_name.length<2||!email.includes('@'))return notifyMsg('Nombre y email son obligatorios.','warn');if(!invite&&password.length<8)return notifyMsg('La contraseña temporal debe tener al menos 8 caracteres.','warn');try{await invokeTeamAdmin(invite?{action:'invite',full_name,email,role}:{action:'create_user',full_name,email,role,password});closeModal();await loadDb();await refreshNativeUsers();renderNativeUsers();notifyMsg(invite?'Invitación enviada.':'Usuario creado.')}catch(e){notifyMsg('No se pudo crear el usuario: '+e.message,'bad')}};

  const baseGoRoot=window.goRoot;
  if(typeof baseGoRoot==='function')window.goRoot=function(root,sub=null){
    if(root!=='users')return baseGoRoot.apply(this,arguments);if(!admin())return baseGoRoot.call(this,'tasks','mine');state.root='users';state.sub='users-home';document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.root==='users'));document.getElementById('iframeShell')?.classList.add('hidden');document.getElementById('main')?.classList.remove('hidden');renderSubnav();renderNativeUsers();refreshNativeUsers().then(renderNativeUsers);if(typeof closeShellNav==='function')closeShellNav()
  };
  const baseGoSub=window.goSub;if(typeof baseGoSub==='function')window.goSub=function(sub){if(state.root==='users'){state.sub='users-home';renderSubnav();renderNativeUsers();return}return baseGoSub.apply(this,arguments)};
})();