import {state} from '../state.js';
import {monthlySummary,clockIn,clockOut,startBreak,stopBreak,stopTask,markNotification} from '../api.js';
import {esc,dateText,dateTimeText,duration,toast,modal,emptyState,card,stat} from '../ui.js';
import {uid,location,myLocations,openAttendance,openBreak,openTaskTime,openInterruption,taskById,fmtElapsed,run} from './shared.js';

export function renderDock(){
  const host=document.getElementById('workDock'),att=openAttendance(),br=openBreak(),tt=openTaskTime(),inter=openInterruption(),task=tt?taskById(tt.task_id):null;
  host.innerHTML=`<div class="dock-state"><span class="dot ${att?'live':''}"></span><div><b>${att?'Jornada activa':'Sin jornada'}</b><small>${att?`${esc(location(att.location_id)?.name||'Centro')} · ${fmtElapsed(att.clock_in)}`:'Pulsa Entrar al comenzar'}</small></div></div><div class="dock-state"><span class="dot ${tt?'live':''}"></span><div><b>${tt?esc(task?.title||'Trabajo en marcha'):'Sin tarea activa'}</b><small>${tt?fmtElapsed(tt.started_at):inter?`Interrupción: ${esc(inter.reason_label||inter.reason_code)}`:'Sin cronómetro'}</small></div></div><div class="dock-state"><span class="dot ${br?'warn':''}"></span><div><b>${br?'Parada personal':'Sin parada'}</b><small>${br?`${esc(br.break_label||br.break_type)} · ${fmtElapsed(br.started_at)}`:'Tiempo personal separado'}</small></div></div><div class="dock-buttons"><button class="${att?'danger':'primary'}" data-action="attendance">${att?'Salir':'Entrar'}</button><button class="secondary" data-action="break" ${!att?'disabled':''}>${br?'Terminar parada':'Parada'}</button>${tt?'<button class="secondary" data-action="stop-task">Parar tarea</button>':''}</div>`;
  host.querySelector('[data-action="attendance"]').onclick=handleAttendance;
  host.querySelector('[data-action="break"]').onclick=handleBreak;
  host.querySelector('[data-action="stop-task"]')?.addEventListener('click',async()=>{await run(async()=>{await stopTask();await window.Totus.reload();toast('Tarea detenida.','ok')})});
}
async function handleAttendance(){const att=openAttendance();if(att){const ok=await modal({title:'Cerrar jornada',message:'Se registrará la salida de este tramo de trabajo.',confirmText:'Cerrar jornada'});if(!ok)return;await run(async()=>{await clockOut();await window.Totus.reload();toast('Jornada cerrada.','ok')});return}const locs=myLocations();if(!locs.length)return toast('No tienes ningún centro asignado.','bad');const html=`<label>Centro<select id="clockLocation">${locs.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></label>`;const ok=await modal({title:'Iniciar jornada',message:'Elige dónde vas a trabajar.',html,confirmText:'Entrar'});if(!ok)return;const id=document.getElementById('clockLocation')?.value||locs[0].id;await run(async()=>{await clockIn(id);await window.Totus.reload();toast('Jornada iniciada.','ok')})}
async function handleBreak(){const br=openBreak();if(br){await run(async()=>{await stopBreak();await window.Totus.reload();toast('Parada terminada.','ok')});return}const types=state.data.breakTypes.filter(x=>x.category==='personal'&&!x.counts_as_work);const html=`<label>Motivo<select id="breakType">${types.map(x=>`<option value="${esc(x.code)}">${esc(x.label)}</option>`).join('')}</select></label><label>Nota opcional<textarea id="breakNote" rows="2"></textarea></label>`;const ok=await modal({title:'Parada personal',message:'Este tiempo quedará separado del tiempo trabajado.',html,confirmText:'Iniciar'});if(!ok)return;await run(async()=>{await startBreak(document.getElementById('breakType').value,document.getElementById('breakNote').value.trim()||null);await window.Totus.reload();toast('Parada iniciada.','ok')})}

export async function renderWork(sub,host){if(sub==='dashboard')return dashboard(host);if(sub==='attendance')return attendance(host);if(sub==='schedule')return schedule(host);return monthly(host)}
async function dashboard(host){const today=new Date().toISOString().slice(0,10),mine=state.data.tasks.filter(x=>x.assigned_to===uid()&&!['done','cancelled'].includes(x.status)),notifs=state.data.notifications.filter(x=>!x.read_at);let summary=null;try{summary=await monthlySummary(uid(),today.slice(0,7)+'-01')}catch{}host.innerHTML=`<div class="stat-grid">${stat('Horas previstas',duration(summary?.expectedMinutes||0),'Se calculan desde tu horario')}${stat('Horas realizadas',duration(summary?.workedMinutes||0),'Descontando pausas personales')}${stat('Balance',`${summary?.balanceMinutes>=0?'+':'−'}${duration(Math.abs(summary?.balanceMinutes||0))}`,summary?.balanceMinutes>=0?'A favor':'Pendientes')}${stat('Tareas abiertas',String(mine.length),'Asignadas a ti')}</div><div class="two-col">${card('Qué tienes ahora',mine.length?mine.slice(0,6).map(taskRow).join(''):emptyState('Sin tareas pendientes','No tienes tareas abiertas asignadas.'),{action:'<button class="secondary" data-goto="tasks">Ver todas</button>'})}${card('Avisos',notifs.length?notifs.slice(0,8).map(notificationRow).join(''):emptyState('Todo al día','No tienes avisos pendientes.'))}</div>`;host.querySelector('[data-goto="tasks"]')?.addEventListener('click',()=>window.Totus.go('tasks','mine'));host.querySelectorAll('[data-notification]').forEach(b=>b.onclick=()=>run(async()=>{await markNotification(b.dataset.notification,false);await window.Totus.reload()}))}
function taskRow(t){return `<div class="list-row"><div><b>${esc(t.title)}</b><small>${esc(location(t.location_id)?.name||'')} · ${t.due_at?dateTimeText(t.due_at):'Sin fecha límite'}</small></div><span class="badge ${t.priority}">${esc(t.priority)}</span></div>`}
function notificationRow(n){return `<button class="list-row button-row" data-notification="${n.id}"><div><b>${esc(n.title)}</b><small>${esc(n.message)}</small></div><span>›</span></button>`}
function attendance(host){const mine=state.data.attendance.filter(x=>x.user_id===uid()).slice(0,60);host.innerHTML=card('Fichajes recientes',mine.length?`<div class="table-wrap"><table><thead><tr><th>Entrada</th><th>Salida</th><th>Centro</th><th>Tiempo bruto</th></tr></thead><tbody>${mine.map(a=>`<tr><td>${dateTimeText(a.clock_in)}</td><td>${dateTimeText(a.clock_out)}</td><td>${esc(location(a.location_id)?.name||'—')}</td><td>${duration(((new Date(a.clock_out||Date.now())-new Date(a.clock_in))/60000))}</td></tr>`).join('')}</tbody></table></div>`:emptyState('Sin fichajes','Todavía no hay fichajes para mostrar.'),{action:'<button class="secondary" data-refresh>Actualizar</button>'});host.querySelector('[data-refresh]').onclick=()=>window.Totus.reload()}
function schedule(host){const rows=state.data.schedules.filter(x=>x.user_id===uid());const grouped=[1,2,3,4,5,6,7].map(day=>[day,rows.filter(x=>x.weekday===day)]);host.innerHTML=card('Mi horario actual',`<div class="schedule-grid">${grouped.map(([d,rs])=>`<div class="schedule-day"><b>${['','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'][d]}</b>${rs.length?rs.map(r=>`<span>${r.start_time.slice(0,5)}–${r.end_time.slice(0,5)} <small>${esc(location(r.location_id)?.name||'')}</small></span>`).join(''):'<span class="muted">Libre</span>'}</div>`).join('')}</div><div class="note">El objetivo mensual se calcula automáticamente con este horario, excepciones, festivos, vacaciones y ajustes de incidencias. No necesitas introducir horas mensuales a mano.</div>`)}
async function monthly(host){const month=new Date().toISOString().slice(0,7)+'-01',summary=await monthlySummary(uid(),month);host.innerHTML=`<div class="stat-grid">${stat('Base del horario',duration(summary.baseMinutes))}${stat('Previstas este mes',duration(summary.expectedMinutes))}${stat('Trabajadas',duration(summary.workedMinutes))}${stat('Balance',`${summary.balanceMinutes>=0?'+':'−'}${duration(Math.abs(summary.balanceMinutes))}`)}</div>${card('Cómo se calcula',`<div class="formula"><div><span>Horario base</span><b>${duration(summary.baseMinutes)}</b></div><div><span>Excepciones de turno</span><b>${summary.exceptionDeltaMinutes>=0?'+':'−'}${duration(Math.abs(summary.exceptionDeltaMinutes))}</b></div><div><span>Festivos</span><b>−${duration(summary.holidayMinutes)}</b></div><div><span>Vacaciones/días que descuentan jornada</span><b>−${duration(summary.leaveMinutes)}</b></div><div><span>Ajustes por incidencias</span><b>${summary.incidentAdjustmentMinutes>=0?'+':'−'}${duration(Math.abs(summary.incidentAdjustmentMinutes))}</b></div><div class="formula-total"><span>Total previsto</span><b>${duration(summary.expectedMinutes)}</b></div></div>`)}${card('Día a día',`<div class="table-wrap"><table><thead><tr><th>Día</th><th>Horario</th><th>Ajustes</th><th>Previsto</th></tr></thead><tbody>${(summary.days||[]).filter(d=>d.base_minutes||d.expected_minutes||d.incident_adjustment_minutes).map(d=>`<tr><td>${dateText(d.work_date)}</td><td>${duration(d.base_minutes)}</td><td>${d.expected_minutes-d.base_minutes>=0?'+':'−'}${duration(Math.abs(d.expected_minutes-d.base_minutes))}</td><td><b>${duration(d.expected_minutes)}</b></td></tr>`).join('')}</tbody></table></div>`)}`}
