import {state,resetState} from './state.js';
import {loadSession,loadCore,loadOperational,signIn,signOut,resetPassword} from './api.js';
import {NAV,SUB,render,renderDock} from './views/index.js';
import {roleLabel,toast,setBusy,esc} from './ui.js';

const login=document.getElementById('login'),app=document.getElementById('app'),mainNav=document.getElementById('mainNav'),subNav=document.getElementById('subNav');
const TITLES={work:'Trabajo y jornada',tasks:'Tareas',purchases:'Compras de empleados',pricing:'Precios',library:'Ayuda y tutoriales',history:'Histórico',users:'Usuarios y permisos'};
const allowed=root=>root!=='users'||state.me?.role==='admin';
function buildNav(){mainNav.innerHTML=NAV.filter(([root])=>allowed(root)).map(([root,label,icon])=>`<button type="button" data-root="${root}" class="nav-btn"><span>${icon}</span><b>${label}</b></button>`).join('');mainNav.querySelectorAll('[data-root]').forEach(b=>b.onclick=()=>go(b.dataset.root))}
function buildSub(){const tabs=SUB[state.route.root]||[];if(!tabs.some(([k])=>k===state.route.sub))state.route.sub=tabs[0]?.[0]||'';subNav.innerHTML=tabs.map(([k,label])=>`<button type="button" data-sub="${k}" class="${state.route.sub===k?'active':''}">${label}</button>`).join('');subNav.querySelectorAll('[data-sub]').forEach(b=>b.onclick=()=>go(state.route.root,b.dataset.sub))}
function paintShell(){document.querySelectorAll('[data-root]').forEach(b=>b.classList.toggle('active',b.dataset.root===state.route.root));document.getElementById('viewTitle').textContent=TITLES[state.route.root]||'Totus Central';document.getElementById('roleChip').textContent=roleLabel(state.me?.role);const member=state.data.members.find(x=>x.email?.toLowerCase()===state.me?.email?.toLowerCase()),assigned=state.data.memberLocations.filter(x=>x.user_id===state.me.id),loc=state.data.locations.find(x=>x.id===assigned.find(x=>x.is_primary)?.location_id)||state.data.locations.find(x=>x.id===assigned[0]?.location_id);document.getElementById('locationChip').textContent=loc?.name||member?.store||'Sin centro';document.getElementById('userMini').innerHTML=`<b>${esc(state.me?.full_name||'Usuario')}</b><span>${esc(state.me?.email||'')}</span>`;buildSub();renderDock()}
export async function go(root,sub){if(!allowed(root)){toast('Zona exclusiva de administración.','bad');return}state.route={root,sub:sub||SUB[root]?.[0]?.[0]||''};location.hash=`#${state.route.root}/${state.route.sub}`;paintShell();await render(state.route.root,state.route.sub);document.getElementById('content').focus({preventScroll:true});closeMobileNav()}
export async function reload(){try{await loadOperational();paintShell();await render(state.route.root,state.route.sub)}catch(e){toast(e.message,'bad')}}
export async function rerender(){paintShell();await render(state.route.root,state.route.sub)}
async function bootstrap(){setBusy(true,'Cargando Totus…');try{await loadCore();if(!state.me)throw new Error('Tu cuenta no tiene perfil activo');login.classList.add('hidden');app.classList.remove('hidden');buildNav();const hash=location.hash.replace(/^#/,'').split('/'),root=allowed(hash[0])&&SUB[hash[0]]?hash[0]:'work',sub=SUB[root].some(([k])=>k===hash[1])?hash[1]:SUB[root][0][0];await go(root,sub);clearInterval(state.refreshTimer);state.refreshTimer=setInterval(reload,60_000);clearInterval(state.tickTimer);state.tickTimer=setInterval(renderDock,1000)}catch(e){resetState();app.classList.add('hidden');login.classList.remove('hidden');setLoginStatus(e.message||'No se pudo iniciar Totus','bad')}finally{setBusy(false)}}
function setLoginStatus(text,type=''){const el=document.getElementById('loginStatus');el.textContent=text;el.className=`form-status ${type}`}
document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();const email=document.getElementById('loginEmail').value.trim().toLowerCase(),password=document.getElementById('loginPassword').value;if(!email||!password)return setLoginStatus('Escribe email y contraseña.','bad');const btn=document.getElementById('loginSubmit');btn.disabled=true;setLoginStatus('Comprobando acceso…');try{await signIn(email,password);await bootstrap()}catch(err){setLoginStatus(err.message||'Acceso no válido','bad')}finally{btn.disabled=false}};
document.getElementById('togglePassword').onclick=()=>{const p=document.getElementById('loginPassword'),show=p.type==='password';p.type=show?'text':'password';document.getElementById('togglePassword').textContent=show?'Ocultar':'Ver'};
document.getElementById('forgotPassword').onclick=async()=>{const email=document.getElementById('loginEmail').value.trim().toLowerCase();if(!email)return setLoginStatus('Escribe primero tu email.','bad');try{setLoginStatus('Preparando recuperación…');await resetPassword(email);setLoginStatus('Correo enviado. Revisa también spam.','ok')}catch(e){setLoginStatus(e.message||'No se pudo enviar el correo','bad')}};
document.getElementById('logoutBtn').onclick=async()=>{await signOut();location.reload()};
document.getElementById('menuBtn').onclick=()=>document.body.classList.toggle('nav-open');document.getElementById('navBackdrop').onclick=closeMobileNav;function closeMobileNav(){document.body.classList.remove('nav-open')}
window.addEventListener('hashchange',()=>{if(!state.me)return;const [root,sub]=location.hash.replace(/^#/,'').split('/');if(SUB[root]&&allowed(root))go(root,sub)});
window.addEventListener('unhandledrejection',e=>{console.error(e.reason);toast(e.reason?.message||'Error inesperado','bad')});
window.Totus={go,reload,render:rerender};
const session=await loadSession();if(session)await bootstrap();