import {supabase,T,all,download,rpc} from './data.js';
const TABLES=Object.values(T).filter((v,i,a)=>a.indexOf(v)===i&&v!=='backup_archives');
const LINKS=[['task_evidence','task-evidence','storage_path'],['employee_documents','employee-documents','storage_path'],['internal_library','internal-library','storage_path'],['team_members','user-avatars','avatar_path']];
const enc=new TextEncoder(),hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
const sha=async x=>hex(await crypto.subtle.digest('SHA-256',typeof x==='string'?enc.encode(x):x));
const to64=b=>new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]||'');r.onerror=no;r.readAsDataURL(b)});
const blob=(s,t='application/octet-stream')=>new Blob([Uint8Array.from(atob(s),c=>c.charCodeAt(0))],{type:t});
async function put(f){const {error}=await supabase.storage.from(f.bucket).upload(f.path,blob(f.data,f.mime),{upsert:true,contentType:f.mime});if(error)throw error}
async function del(f){const {error}=await supabase.storage.from(f.bucket).remove([f.path]);if(error)throw error}
export async function createBackup(){const tables={};for(const t of TABLES)tables[t]=await all(t,null);const files=[];for(const [table,bucket,key] of LINKS)for(const row of tables[table]||[]){const path=row[key];if(!path)continue;const b=await download(bucket,path),bytes=await b.arrayBuffer();files.push({bucket,path,mime:b.type||'application/octet-stream',size:bytes.byteLength,sha256:await sha(bytes),data:await to64(b)})}const tableText=JSON.stringify(tables),index=JSON.stringify(files.map(({bucket,path,mime,size,sha256})=>({bucket,path,mime,size,sha256})).sort((a,b)=>(a.bucket+a.path).localeCompare(b.bucket+b.path)));const payload={format:'totus-central-backup',version:1,created_at:new Date().toISOString(),tables,files,manifest:{tables_sha256:await sha(tableText),files_index_sha256:await sha(index),file_count:files.length,total_file_bytes:files.reduce((a,b)=>a+b.size,0)}};const raw=JSON.stringify(payload);payload.package_sha256=await sha(raw);return {payload,text:JSON.stringify(payload),name:`totus-central-${new Date().toISOString().replace(/[:.]/g,'-')}.totusbackup`}}
export async function validateBackup(p){if(!p||p.format!=='totus-central-backup'||p.version!==1)throw Error('Formato de backup no válido');for(const t of TABLES)if(!Array.isArray(p.tables?.[t]))throw Error(`Falta la tabla ${t}`);if(await sha(JSON.stringify(p.tables))!==p.manifest?.tables_sha256)throw Error('Checksum de datos incorrecto');const idx=JSON.stringify((p.files||[]).map(({bucket,path,mime,size,sha256})=>({bucket,path,mime,size,sha256})).sort((a,b)=>(a.bucket+a.path).localeCompare(b.bucket+b.path)));if(await sha(idx)!==p.manifest?.files_index_sha256)throw Error('Checksum de archivos incorrecto');for(const f of p.files||[]){const bytes=Uint8Array.from(atob(f.data),c=>c.charCodeAt(0));if(bytes.length!==f.size||await sha(bytes.buffer)!==f.sha256)throw Error(`Archivo dañado: ${f.path}`)}return true}
export async function restoreBackup(p){await validateBackup(p);const safe=await createBackup(),incoming=new Set(p.files.map(f=>`${f.bucket}|${f.path}`));try{for(const f of p.files)await put(f);await rpc('admin_restore_backup_payload',{p_tables:p.tables});for(const f of safe.payload.files)if(!incoming.has(`${f.bucket}|${f.path}`))await del(f)}catch(e){for(const f of safe.payload.files)await put(f);await rpc('admin_restore_backup_payload',{p_tables:safe.payload.tables});const old=new Set(safe.payload.files.map(f=>`${f.bucket}|${f.path}`));for(const f of p.files)if(!old.has(`${f.bucket}|${f.path}`))try{await del(f)}catch{}throw e}return true}
export function downloadText(text,name){const u=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
