import {supabase,T,all,download,upload,rpc} from './data.js';
const TABLES=Object.values(T).filter((v,i,a)=>a.indexOf(v)===i&&!['backup_archives'].includes(v));
const LINKS=[['task_evidence','task-evidence','storage_path'],['employee_documents','employee-documents','storage_path'],['internal_library','internal-library','storage_path'],['team_members','user-avatars','avatar_path']];
const enc=new TextEncoder();
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
const sha=async s=>hex(await crypto.subtle.digest('SHA-256',typeof s==='string'?enc.encode(s):s));
const blob64=b=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]||'');r.onerror=rej;r.readAsDataURL(b)});
const b64blob=(s,type='application/octet-stream')=>new Blob([Uint8Array.from(atob(s),c=>c.charCodeAt(0))],{type});
export async function createBackup(){const tables={};for(const t of TABLES)tables[t]=await all(t,null);const files=[];for(const [table,bucket,key] of LINKS){for(const row of tables[table]||[]){const path=row[key];if(!path)continue;const blob=await download(bucket,path);const bytes=await blob.arrayBuffer();files.push({bucket,path,mime:blob.type||'application/octet-stream',size:bytes.byteLength,sha256:await sha(bytes),data:await blob64(blob)})}}
const tablesJson=JSON.stringify(tables);const fileIndex=JSON.stringify(files.map(({bucket,path,mime,size,sha256})=>({bucket,path,mime,size,sha256})).sort((a,b)=>(a.bucket+a.path).localeCompare(b.bucket+b.path)));const payload={format:'totus-central-backup',version:1,created_at:new Date().toISOString(),tables,files,manifest:{tables_sha256:await sha(tablesJson),files_index_sha256:await sha(fileIndex),file_count:files.length,total_file_bytes:files.reduce((a,b)=>a+b.size,0)}};const text=JSON.stringify(payload);payload.package_sha256=await sha(text);return {payload,text:JSON.stringify(payload),name:`totus-central-${new Date().toISOString().replace(/[:.]/g,'-')}.totusbackup`}}
export async function validateBackup(p){if(!p||p.format!=='totus-central-backup'||p.version!==1)throw new Error('Formato de backup no válido');if(!p.tables||!p.files||!p.manifest)throw new Error('Backup incompleto');for(const t of TABLES)if(!Array.isArray(p.tables[t]))throw new Error(`Falta la tabla ${t}`);const tHash=await sha(JSON.stringify(p.tables));if(tHash!==p.manifest.tables_sha256)throw new Error('Checksum de datos incorrecto');const idx=JSON.stringify(p.files.map(({bucket,path,mime,size,sha256})=>({bucket,path,mime,size,sha256})).sort((a,b)=>(a.bucket+a.path).localeCompare(b.bucket+b.path)));if(await sha(idx)!==p.manifest.files_index_sha256)throw new Error('Checksum de archivos incorrecto');for(const f of p.files){const bytes=Uint8Array.from(atob(f.data),c=>c.charCodeAt(0));if(bytes.length!==f.size||await sha(bytes.buffer)!==f.sha256)throw new Error(`Archivo dañado: ${f.path}`)}return true}
export async function restoreBackup(p){await validateBackup(p);const safety=await createBackup();for(const f of p.files)await upload(f.bucket,f.path,b64blob(f.data,f.mime));try{await rpc('admin_restore_backup_payload',{p_tables:p.tables})}catch(err){for(const f of safety.payload.files)await upload(f.bucket,f.path,b64blob(f.data,f.mime));await rpc('admin_restore_backup_payload',{p_tables:safety.payload.tables});throw err}return true}
export function downloadText(text,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
