import {esc,option} from './core.js';
const e=esc, weekdays=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'];
const field=(label,name,value='',type='text',extra='')=>`<label>${e(label)}<input name="${e(name)}" type="${type}" value="${e(value??'')}" ${extra}></label>`;
const select=(label,name,items,current='',extra='')=>`<label>${e(label)}<select name="${e(name)}" ${extra}>${items.map(x=>option(x[0],x[1],current)).join('')}</select></label>`;
const modal=(title,body,wide=false)=>`<div class="modal-backdrop" data-close-modal><section class="modal ${wide?'wide':''}" role="dialog" aria-modal="true"><header><h2>${e(title)}</h2><button class="icon-button" type="button" data-close-modal>✕</button></header><div class="modal-body">${body}</div></section></div>`;
export function schedulePlanModal(ctx){const m=ctx.base.members.find(x=>x.active)||ctx.me,l=ctx.base.locations[0];return modal('Horario de empleado',`<form id="schedulePlanForm" class="form-stack">${select('Empleado','member_id',ctx.base.members.filter(x=>x.active).map(x=>[x.id,x.name]),m.id)}${select('Tienda','location_id',ctx.base.locations.map(x=>[x.id,x.name]),l?.id||'')}${field('Válido desde','valid_from',new Date().toISOString().slice(0,10),'date','required')}<fieldset><legend>Semana</legend>${weekdays.map((w,i)=>`<div class="form-grid two"><label class="check"><input type="checkbox" name="off_${i+1}"> ${w} libre</label><span></span>${field(`${w} entrada`,`start_${i+1}`,'09:00','time')}${field(`${w} salida`,`end_${i+1}`,'14:00','time')}${field(`${w} 2ª entrada`,`split_start_${i+1}`,'','time')}${field(`${w} 2ª salida`,`split_end_${i+1}`,'','time')}</div>`).join('')}</fieldset><button class="primary" type="submit">Guardar horario</button></form>`,true)}
export function openingPlanModal(ctx){const l=ctx.base.locations[0];return modal('Horario de tienda',`<form id="openingPlanForm" class="form-stack">${select('Tienda','location_id',ctx.base.locations.map(x=>[x.id,x.name]),l?.id||'')}${field('Válido desde','valid_from',new Date().toISOString().slice(0,10),'date','required')}${field('Válido hasta','valid_to','','date')}${field('Temporada','season_name','General')}<fieldset><legend>Semana</legend>${weekdays.map((w,i)=>`<div class="form-grid two"><label class="check"><input type="checkbox" name="closed_${i+1}"> ${w} cerrado</label><span></span>${field(`${w} apertura`,`start_${i+1}`,'10:00','time')}${field(`${w} cierre`,`end_${i+1}`,'14:00','time')}${field(`${w} 2ª apertura`,`split_start_${i+1}`,'17:00','time')}${field(`${w} 2ª cierre`,`split_end_${i+1}`,'20:30','time')}</div>`).join('')}</fieldset><button class="primary" type="submit">Guardar horario</button></form>`,true)}
export function scheduleExceptionModal(ctx){return modal('Excepción de empleado',`<form id="scheduleExceptionForm" class="form-stack">${select('Empleado','member_id',ctx.base.members.filter(x=>x.active).map(x=>[x.id,x.name]),ctx.me.id)}${field('Fecha','exception_date','','date','required')}<label class="check"><input type="checkbox" name="off"> Día libre</label><div class="form-grid two">${field('Entrada','start_time','','time')}${field('Salida','end_time','','time')}</div>${field('Motivo','reason','','text','required')}<button class="primary" type="submit">Guardar excepción</button></form>`)}
export function openingExceptionModal(ctx){return modal('Excepción de tienda',`<form id="openingExceptionForm" class="form-stack">${select('Tienda','location_id',ctx.base.locations.map(x=>[x.id,x.name]),ctx.base.locations[0]?.id||'')}${field('Fecha','exception_date','','date','required')}<label class="check"><input type="checkbox" name="closed"> Cerrado</label><div class="form-grid two">${field('Apertura','start_time','','time')}${field('Cierre','end_time','','time')}</div>${field('Motivo','reason','','text','required')}<button class="primary" type="submit">Guardar excepción</button></form>`)}
export function activationModal(email=''){return modal('Activar mi acceso',`<form id="activationForm" class="form-stack">${field('Email','email',email,'email','required autocomplete="email"')}${field('Nueva contraseña','password','','password','required minlength="8" autocomplete="new-password"')}${field('Repetir contraseña','password2','','password','required minlength="8" autocomplete="new-password"')}<p class="inline-note">Recibirás un correo para confirmar la cuenta. Después podrás entrar con esta contraseña.</p><button class="primary" type="submit">Crear acceso</button></form>`)}
export function interruptionModal(){return modal('Interrupción laboral',`<form id="interruptionForm" class="form-stack">${field('Motivo','reason','','text','required')}<p class="inline-note">La interrupción laboral sí cuenta como tiempo de trabajo.</p><button class="primary" type="submit">Comenzar interrupción</button></form>`)}
export function soundModal(){const ls=typeof localStorage==='undefined'?null:localStorage,muted=ls?.getItem('totus.notice.muted')==='1',vol=Number(ls?.getItem('totus.notice.volume')||'0.6');return modal('Sonido de avisos',`<form id="soundForm" class="form-stack"><label class="check"><input type="checkbox" name="muted" ${muted?'checked':''}> Silenciar avisos en este dispositivo</label><label>Volumen<input type="range" name="volume" min="0" max="1" step="0.1" value="${vol}"></label><div class="actions"><button class="secondary" type="button" data-action="sound-test">Probar sonido</button><button class="primary" type="submit">Guardar</button></div></form>`)}
export function purchaseStatusModal(row){return modal('Estado de compra',`<form id="purchaseStatusForm" class="form-stack" data-id="${row.id}">${select('Estado','status',[['pending','Pendiente'],['approved','Aprobada'],['delivered','Entregada'],['cancelled','Cancelada']],row.status)}<button class="primary" type="submit">Guardar estado</button></form>`)}
export function noticeCancelModal(id){return modal('Cancelar aviso',`<form id="noticeCancelForm" class="form-stack" data-id="${id}">${field('Motivo','reason','','text','required')}<button class="danger" type="submit">Cancelar aviso</button></form>`)}
export function backupRestoreModal(p){return modal('Restaurar backup',`<form id="backupRestoreForm" class="form-stack"><div class="warning-box"><strong>Backup verificado</strong><p>${e(p.created_at||'')} · ${p.manifest?.file_count||0} archivos · ${Math.round((p.manifest?.total_file_bytes||0)/1024)} KB físicos.</p></div><p>Antes de restaurar se genera una copia de seguridad automática. La restauración sustituye los datos por el contenido del paquete.</p><button class="danger" type="submit">Restaurar backup</button></form>`)}
export function pricingSettingsModal(s={}){return modal('Ajustes de Pricing',`<form id="pricingSettingsForm" class="form-stack"><div class="form-grid two">${field('IVA %','vat',s.vat??21,'text','inputmode="decimal"')}${field('Recargo %','re',s.re??5.2,'text','inputmode="decimal"')}${field('Margen crítico %','critical',s.critical??15,'text','inputmode="decimal"')}${field('Margen ajustado %','tight',s.tight??25,'text','inputmode="decimal"')}${field('Margen sano %','healthy',s.healthy??35,'text','inputmode="decimal"')}${field('Mínimo promo %','min_promo',s.min_promo??18,'text','inputmode="decimal"')}${field('Tolerancia mercado %','market_tolerance',s.market_tolerance??3,'text','inputmode="decimal"')}</div><button class="primary" type="submit">Guardar ajustes</button></form>`)}
