import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
const backup=read('totus-backup.js'),team=read('totus-team.js'),rbac=read('totus-rbac.js'),records=read('totus-employee-records.js'),index=read('index.html');
const fail=[],ok=[],check=(c,m)=>c?ok.push(m):fail.push(m);
check(/CURRENT_VERSION=4/.test(backup),'Backup portable actual usa versión 4');
check(/V3_TABLES/.test(backup)&&/V4_TABLES/.test(backup),'Backup separa esquemas V3 y V4');
check(/employee_incidents/.test(backup)&&/employee_documents/.test(backup),'Backup V4 incluye incidencias y documentación de empleado');
check(/employee-documents/.test(backup),'Backup V4 incluye bucket documental privado');
check(/\[1,2,3,4\]/.test(backup),'Validador mantiene compatibilidad V1/V2/V3/V4');
check(/admin_rebuild_member_locations_legacy/.test(backup),'Backups V1/V2 reconstruyen asignaciones heredadas');
check(/admin_validate_backup_auth/.test(backup),'Rollback exacto mantiene preflight de Auth');
check(/createSafetyBackup/.test(backup),'Rollback/restauración crea copia previa');
check(/verifyRestoredBackup/.test(backup),'Rollback/restauración verifica integridad');
check(/user-avatars/.test(team),'Copia histórica mantiene avatares');
check(/task-evidence/.test(team)&&/internal-library/.test(team),'Copia histórica mantiene evidencias y biblioteca');
check(/totus-rbac\.js/.test(index),'Shell carga RBAC');
check(/totus-employee-records\.js/.test(index),'Shell carga expediente de empleado');
check(/canManageTeam/.test(rbac)&&/canSuperviseTeam/.test(rbac),'RBAC separa gerencia y supervisión');
check(/canManageUsers=systemAdmin/.test(rbac)&&/canManageBackups=systemAdmin/.test(rbac),'Usuarios y backup siguen solo Admin');
check(/sub==='stores'&&!systemAdmin/.test(rbac),'Ruta de centros se protege en cliente');
check(/sub==='maintenance'&&!systemAdmin/.test(rbac),'Ruta de mantenimiento se protege en cliente');
check(/\['admin','gerente','encargado'\]/.test(rbac),'Encargado está en supervisión operativa');
check(/\['admin','gerente'\]/.test(rbac),'Gerente está en gestión operativa');
check(/\['incidents','Incidencias'\]/.test(rbac)&&/\['documents','Documentación'\]/.test(rbac),'Navegación supervisora incluye expediente nuevo');
check(/employee_incidents/.test(records)&&/employee_incident_audit_log/.test(records),'Frontend carga incidencias y auditoría');
check(/employee_documents/.test(records)&&/employee_document_audit_log/.test(records),'Frontend carga documentación y auditoría');
check(/employee-documents/.test(records),'Frontend usa bucket documental dedicado');
check(/archiveEmployeeDocument/.test(records)&&/restoreEmployeeDocument/.test(records),'Documentos se archivan/reactivan sin borrado funcional');
check(!/\.delete\(/.test(records),'Expediente no borra registros de negocio desde frontend');
if(fail.length){console.error('BACKUP/RBAC/EXPEDIENTE QA FALLIDA');fail.forEach(x=>console.error('✗ '+x));process.exit(1)}
console.log(`BACKUP/RBAC/EXPEDIENTE QA OK · ${ok.length}`);ok.forEach(x=>console.log('✓ '+x));