import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import fs from 'node:fs';
const out='qa-artifacts';fs.mkdirSync(out,{recursive:true});
const server=spawn('python3',['-m','http.server','4173','--bind','127.0.0.1'],{stdio:'ignore'});await new Promise(r=>setTimeout(r,700));
const now=new Date(),before=m=>new Date(Date.now()-m*60000).toISOString();
const people=[
 {id:'u1',name:'Diego QA',email:'admin@example.test',role:'admin',jobTitle:'Administrador / CO',active:true,avatarUrl:null},
 {id:'u2',name:'Davinia QA',email:'gerente@example.test',role:'gerente',jobTitle:'Gerente',active:true,avatarUrl:null},
 {id:'u3',name:'Óscar QA',email:'encargado@example.test',role:'encargado',jobTitle:'Encargado',active:true,avatarUrl:null},
 {id:'u4',name:'Tendero QA',email:'tendero@example.test',role:'tendero',jobTitle:'Atención de tienda',active:true,avatarUrl:null},
 {id:'u5',name:'Invitado QA',email:'invitado@example.test',role:'invitado',jobTitle:'Consulta',active:true,avatarUrl:null}
];
const locations=[{id:'l1',name:'Hortimatic',code:'HORTI',active:true},{id:'l2',name:'NewOldSmok',code:'NOS',active:true},{id:'l3',name:'TotusCode',code:'TCODE',active:true,workspace_type:'digital_project',work_mode:'hybrid'}];
const memberLocations=[...people.flatMap((p,i)=>[{user_id:p.id,location_id:i===2?'l1':i===4?'l3':'l1',active:true},{user_id:p.id,location_id:i===2?'l2':'l3',active:true}])];
const base={people,team:people.map(p=>({email:p.email,full_name:p.name,role:p.role,active:true,job_title:p.jobTitle})),memberLocations,locations,settings:{employee_purchase_rules:{vat_pct:21,re_pct:5.2,store_discount_pct:10}},
 breakTypes:[{code:'smoke',label:'Cigarro',category:'personal',counts_as_work:false,active:true,requires_note:false,sort_order:10},{code:'medical_call',label:'Llamada personal',category:'personal',counts_as_work:false,active:true,requires_note:true,sort_order:20},{code:'sales_rep_visit',label:'Visita comercial',category:'work',counts_as_work:true,active:true,requires_note:false,sort_order:100}],
 taskCategories:[{id:'c1',code:'customer_service',name:'Atención al cliente',active:true,sort_order:10},{id:'c2',code:'lead_prospecting',name:'Prospección / leads',active:true,sort_order:20}],targets:[],schedules:[],scheduleExceptions:[],openingHours:[],openingExceptions:[],
 attendance:[{id:'a1',user_id:'u1',location_id:'l1',clock_in:before(220),clock_out:null},{id:'a2',user_id:'u2',location_id:'l3',clock_in:before(160),clock_out:null}],
 tasks:[{id:'t1',title:'Revisar pedidos',description:'Control de proveedor',assigned_to:'u1',location_id:'l1',category_id:'c1',priority:'high',status:'doing',starts_at:before(90),due_at:before(-90),created_at:before(400),estimated_minutes:120,requires_evidence:false,recurrence:{enabled:false}},{id:'t2',title:'Prospección empresas',description:'Buscar leads',assigned_to:'u2',location_id:'l3',category_id:'c2',priority:'normal',status:'pending',starts_at:before(10),due_at:before(-180),created_at:before(300),estimated_minutes:90,requires_evidence:false,recurrence:{enabled:false}}],
 taskTimes:[{id:'tt1',task_id:'t1',user_id:'u1',started_at:before(40),stopped_at:null}],taskTimeAudit:[],interruptions:[],signatures:[],purchases:[],purchaseAudit:[],breaks:[],attendanceAudit:[],overruns:[],taskAudit:[],adminAudit:[],consultationHistory:[],priceHistory:[],userAudit:[],emailLog:[],library:[],libraryAudit:[],
 leaveSettings:people.map(p=>({user_id:p.id,accrual_rate:2.5,annual_cap:30})),leavePeriods:[{id:'lv1',user_id:'u1',leave_type_code:'vacation',start_date:now.toISOString().slice(0,10),end_date:now.toISOString().slice(0,10),natural_days:1,status:'active',label:'Vacaciones'}],leaveTypes:[{code:'vacation',label:'Vacaciones',active:true,sort_order:10},{code:'gift',label:'Día regalado',active:true,sort_order:20},{code:'medical',label:'Asunto médico',active:true,sort_order:30},{code:'personal_management',label:'Gestión / asunto personal',active:true,sort_order:40},{code:'other',label:'Otra ausencia',active:true,sort_order:50}],holidays:[],leaveRequests:[],notifications:[],evidence:[],questions:[],backups:[],maintenanceLog:[],
 incidents:[{id:'i1',user_id:'u1',location_id:'l1',incident_date:now.toISOString().slice(0,10),category:'operational',severity:'normal',title:'Incidencia de prueba',description:'Descripción controlada',status:'open',created_at:before(80),created_by:'u1'}],incidentAudit:[],employeeDocuments:[{id:'d1',user_id:'u1',category:'training',title:'Formación interna',file_name:'formacion.pdf',file_path:'u1/formacion.pdf',active:true,created_at:before(120)}],employeeDocumentAudit:[]};
const screens={admin:['mine','overview','calendar','tasks','schedule','leave','attendance','incidents','documents','reports','stores'],gerente:['mine','overview','calendar','tasks','schedule','leave','attendance','incidents','documents','reports'],encargado:['mine','overview','calendar','tasks','schedule','leave','attendance','incidents','documents','reports'],tendero:['mine','calendar','tasks','schedule','leave','attendance','incidents','documents','reports'],invitado:['mine','calendar','tasks','schedule','leave','attendance','incidents','documents','reports']};
const views=[['wide',1600,1000],['desktop',1280,900],['laptop',1024,900],['tablet',768,900],['mobile',430,900],['small',360,800]];
const issues=[],rows=[];let renders=0;const browser=await chromium.launch({headless:true});
try{for(const [vp,w,h] of views){for(const p of people){const ctx=await browser.newContext({viewport:{width:w,height:h},locale:'es-ES',timezoneId:'Europe/Madrid'}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto('http://127.0.0.1:4173/index.html',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>typeof renderTasks==='function'&&typeof employeeContextCardHtml==='function',{timeout:15000});await page.evaluate(({base,uid})=>{(0,eval)(`session={user:{id:'${uid}',email:'${base.people.find(x=>x.id===uid).email}'}};Object.assign(db,globalThis.__base);document.getElementById('loginView').classList.add('hidden');document.getElementById('appView').classList.remove('hidden');paintUser();state.root='tasks';state.sub='mine';renderSubnav();renderTasks();tick();`);},{base,uid:p.id});await page.waitForTimeout(80);
for(const sub of screens[p.role]){await page.evaluate(sub=>{state.root='tasks';state.sub=sub;renderSubnav();renderTasks()},sub);await page.waitForTimeout(70);const m=await page.evaluate(()=>{const main=document.getElementById('main'),cards=[...main.querySelectorAll(':scope > .employee-context-card')],sel=document.querySelectorAll('#employeeContextSelect').length,bodyOver=document.documentElement.scrollWidth-document.documentElement.clientWidth,mainOver=main.scrollWidth-main.clientWidth;let min=99;for(const el of main.querySelectorAll('*')){if(!el.textContent?.trim())continue;const n=parseFloat(getComputedStyle(el).fontSize);if(n>0)min=Math.min(min,n)}return{contextCards:cards.length,selector:sel,bodyOver,mainOver,min:min===99?0:min,sidebarCollapsed:document.body.classList.contains('shell-sidebar-collapsed')}});renders++;rows.push({vp,role:p.role,sub,...m});if(sub!=='stores'&&m.contextCards!==1)issues.push(`${vp}/${p.role}/${sub}: ficha común ${m.contextCards}`);if(sub==='stores'&&m.contextCards!==0)issues.push(`${vp}/${p.role}/${sub}: ficha no debe aparecer en configuración`);if(p.role==='admin'&&m.selector!==1)issues.push(`${vp}/${p.role}/${sub}: selector admin ${m.selector}`);if(p.role!=='admin'&&m.selector!==0)issues.push(`${vp}/${p.role}/${sub}: selector indebido ${m.selector}`);if(m.bodyOver>3)issues.push(`${vp}/${p.role}/${sub}: overflow body ${m.bodyOver}`);if(m.mainOver>3)issues.push(`${vp}/${p.role}/${sub}: overflow main ${m.mainOver}`);if(m.min&&m.min<9.5)issues.push(`${vp}/${p.role}/${sub}: microtexto ${m.min}`)}
if(p.role==='admin'&&w>1180){await page.evaluate(()=>toggleSidebarCollapsed(true));await page.waitForTimeout(30);const collapsed=await page.evaluate(()=>document.body.classList.contains('shell-sidebar-collapsed')&&getComputedStyle(document.querySelector('.top')).width==='78px');if(!collapsed)issues.push(`${vp}/admin: sidebar no se recoge correctamente`);await page.evaluate(()=>toggleSidebarCollapsed(false))}
for(const e of errors)issues.push(`${vp}/${p.role}: pageerror ${e}`);await ctx.close()}}
}finally{await browser.close();server.kill('SIGTERM')}
fs.writeFileSync(`${out}/reference-ui-metrics.json`,JSON.stringify(rows,null,2));fs.writeFileSync(`${out}/reference-ui-issues.txt`,issues.join('\n'));console.log(`Reference UI QA · ${renders} renderizados · ${issues.length} incidencias`);if(renders<280){console.error('✗ Batería insuficiente: '+renders);process.exit(1)}if(issues.length){issues.slice(0,150).forEach(x=>console.error('✗ '+x));process.exit(1)}